// Builds game.html, the full game page (scene 1 -> scene 2), from scene 1's page in
// assets/incoming/scene1/. Scene 1 stays byte for byte as delivered; only the scene 2
// container and src/scene1Bridge.js are added before </body>. Re-run when scene 1
// sends a new version:  npm run scene1
import { readFileSync, writeFileSync } from 'node:fs';
import { scene1SourceFile } from './scene1-characters.mjs';

const file = scene1SourceFile();
const src = readFileSync(file, 'utf8');
const end = src.lastIndexOf('</body>');
if (end < 0 || !src.includes('window.LannaphaGame')) throw new Error(`${file}: no </body> or no LannaphaGame API`);

const notice = `<!-- game.html: generated by tools/scene1-page.mjs from ${file}. Do not edit by hand. -->\n`;
const add = `<!-- Scene 2 (added by tools/scene1-page.mjs): plugs into scene 1 with LannaphaGame.registerScene. -->
<div id="game" hidden></div>
<script type="module" src="/src/scene1Bridge.js"></script>
`;
const afterDoctype = src.indexOf('\n') + 1; // keep <!DOCTYPE html> first
writeFileSync('game.html', src.slice(0, afterDoctype) + notice + src.slice(afterDoctype, end) + add + src.slice(end));
console.log(`game.html: ${file} + scene 2 bridge`);
