// Builds game.html, the full game page (scene 1 -> scene 2), from scene 1's page in
// assets/incoming/scene1/ (kept exactly as delivered). Adds the scene 2 container and
// src/scene1Bridge.js before </body>, and applies the owner's edits to scene 1 (EDITS
// below: exact find/replace, each must match once, or the build stops so a new scene 1
// version is checked by hand). Re-run when scene 1 sends a new version:  npm run scene1
import { readFileSync, writeFileSync } from 'node:fs';
import { scene1SourceFile } from './scene1-characters.mjs';

// Owner edits to scene 1's home screen: the event's own Instagram (@laanapha) as the
// main social button. Bottom rows become [start | tickets] and [IG LAANAPHA | IG JAYIMPACTS].
const EDITS = [
  {
    what: 'event Instagram URL',
    find: "const FOLLOW_URL = 'https://www.instagram.com/jayimpacts/';",
    replace: "const FOLLOW_URL = 'https://www.instagram.com/jayimpacts/';\nconst EVENT_IG_URL = 'https://www.instagram.com/laanapha/';   /* owner edit: the event's main Instagram */",
  },
  {
    what: 'hook for the event Instagram',
    find: '{ onStart:null, onTickets:null, onFollow:null, onConfirm:null }',
    replace: '{ onStart:null, onTickets:null, onFollow:null, onEventIg:null, onConfirm:null }',
  },
  {
    what: 'home buttons: start + tickets, then the two Instagram buttons',
    find: 'start:{x:30,y:246,w:120,h:18}, tickets:{x:10,y:269,w:64,h:18}, follow:{x:78,y:269,w:92,h:18} };',
    replace: 'start:{x:4,y:246,w:118,h:18}, tickets:{x:128,y:246,w:48,h:18}, eventig:{x:4,y:269,w:84,h:18}, follow:{x:92,y:269,w:84,h:18} };',
  },
  {
    what: 'event Instagram icon: the IG camera in event colours, its lens a jack-o-lantern',
    find: 'function drawIgLabel(b,p,label){',
    replace: `const IG_EVENT = sprite(15,15,(x,y)=>{   /* owner edit: IG glyph, yellow, pumpkin lens = the fest's own IG */
  if ((x===0||x===14) && (y===0||y===14)) return null;
  const ring = (x===2||x===12) ? (y>=3&&y<=11) : (y===2||y===12) ? (x>=3&&x<=11) : false;
  const lens = ((x-7)**2 + (y-7.5)**2) <= 7.5, rim = lens && ((x-7)**2 + (y-7.5)**2) > 4.5;
  if (x===10 && y===4) return COL.black;                                                 /* flash */
  if (x===7 && (y===4||y===3)) return COL.green;                                         /* pumpkin stem */
  if (rim) return COL.black;
  if (lens) return ((x===6||x===8) && y===7) || (y===9 && x>=6 && x<=8) ? COL.black : COL.orange;   /* jack-o-lantern face */
  if (ring) return COL.black;
  return COL.yellow; });
function drawEventIg(b,t){ const p = pressed === 'eventig', o = p ? 1 : 0;   /* main social button: start-button style */
  ctx.fillStyle = COL.yellow; ctx.fillRect(b.x-1,b.y-1+o,b.w+2,b.h+2); ctx.fillStyle = p ? COL.yellow : COL.magenta; ctx.fillRect(b.x,b.y+o,b.w,b.h);
  if (!p){ ctx.fillStyle = COL.dmagenta; ctx.fillRect(b.x,b.y+b.h-2,b.w,2); }
  const label = 'LAANAPHA', tw = label.length*6-1, gw = IG_EVENT.width+4+tw, x0 = Math.round(b.x+(b.w-gw)/2);
  ctx.drawImage(IG_EVENT,x0,b.y+1+o); text(label, x0+IG_EVENT.width+4, b.y+6+o, COL.black, 'l');
  if (Math.floor(t*2) % 2 === 0) sparkle(b.x+b.w-2, b.y, true); }
function drawIgLabel(b,p,label){`,
  },
  {
    what: 'open the event Instagram',
    find: "  else if (id === 'follow'){",
    replace:
      "  else if (id === 'eventig'){ sfx('blip'); if (typeof hooks.onEventIg === 'function') hooks.onEventIg(); else openLink(EVENT_IG_URL,'INSTAGRAM.COM/LAANAPHA'); }\n  else if (id === 'follow'){",
  },
  {
    what: 'draw the event Instagram button',
    find: "button('follow','JAYIMPACTS','small',t,false);",
    replace: "button('follow','JAYIMPACTS','small',t,false); drawEventIg(BTN.eventig,t);",
  },
];

const file = scene1SourceFile();
let src = readFileSync(file, 'utf8');
for (const e of EDITS) {
  const n = src.split(e.find).length - 1;
  if (n !== 1) throw new Error(`${file}: edit "${e.what}" matches ${n} times (expected 1); check the new scene 1 by hand`);
  src = src.replace(e.find, () => e.replace);
}
const end = src.lastIndexOf('</body>');
if (end < 0 || !src.includes('window.LannaphaGame')) throw new Error(`${file}: no </body> or no LannaphaGame API`);

const notice = `<!-- game.html: generated by tools/scene1-page.mjs from ${file} (+ ${EDITS.length} owner edits listed there). Do not edit by hand. -->\n`;
const add = `<!-- Scene 2 (added by tools/scene1-page.mjs): plugs into scene 1 with LannaphaGame.registerScene. -->
<div id="game" hidden></div>
<script type="module" src="/src/scene1Bridge.js"></script>
`;
const afterDoctype = src.indexOf('\n') + 1; // keep <!DOCTYPE html> first
writeFileSync('game.html', src.slice(0, afterDoctype) + notice + src.slice(afterDoctype, end) + add + src.slice(end));
console.log(`game.html: ${file} + ${EDITS.length} owner edits + scene 2 bridge`);
